name = "inertia_wisp"
version = "0.1.0"

description = "Inertia.js adapter for the Wisp web framework"
licences = ["MIT"]
repository = { type = "github", user = "team-alembic", repo = "inertia-wisp" }

[dependencies]
gleam_stdlib = ">= 0.60.0"
wisp = ">= 2.1.0 and < 3.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
