name = "simple_demo"
version = "1.0.0"
description = "Simple demo showcasing inertia wisp"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0"
gleam_http = ">= 4.0.0"
gleam_json = ">= 3.0.0"
wisp = ">= 2.0.0"
inertia_wisp = { path = "../../" }
simplifile = ">= 2.2.1 and < 3.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
mist = ">= 5.0.0"
nodejs = ">= 3.1.3 and < 4.0.0"
sqlight = ">= 1.0.1 and < 2.0.0"
esqlite = ">= 0.9.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
